---
kind: pipeline
name: Lint

steps:
    - name: Lint
      image: python:3.8
      environment:
          PIP_OPTIONS:
              from_secret: pip_options
      commands:
          - pip install $PIP_OPTIONS -r requirements-lint.txt
          - make lint

---
kind: pipeline
name: Test

steps:
    - name: "Python 3.6"
      image: python:3.6
      environment:
          BASEPLATE_CASSANDRA_ADDR: "cassandra:9042"
          BASEPLATE_MEMCACHED_ADDR: "memcached:11211"
          BASEPLATE_REDIS_ADDR: "redis:6379"
          BASEPLATE_VAULT_ADDR: "vault:8200"
          BASEPLATE_ZOOKEEPER_ADDR: "zookeeper:2181"
          PIP_OPTIONS:
              from_secret: pip_options
      commands:
          - pip install $PIP_OPTIONS -r requirements-test.txt
          - pytest
      depends_on: [clone]

    - name: "Python 3.7"
      image: python:3.7
      environment:
          BASEPLATE_CASSANDRA_ADDR: "cassandra:9042"
          BASEPLATE_MEMCACHED_ADDR: "memcached:11211"
          BASEPLATE_REDIS_ADDR: "redis:6379"
          BASEPLATE_VAULT_ADDR: "vault:8200"
          BASEPLATE_ZOOKEEPER_ADDR: "zookeeper:2181"
          PIP_OPTIONS:
              from_secret: pip_options
      commands:
          - pip install $PIP_OPTIONS -r requirements-test.txt
          - pytest
      depends_on: [clone]

    - name: "Python 3.8"
      image: python:3.8
      environment:
          BASEPLATE_CASSANDRA_ADDR: "cassandra:9042"
          BASEPLATE_MEMCACHED_ADDR: "memcached:11211"
          BASEPLATE_REDIS_ADDR: "redis:6379"
          BASEPLATE_VAULT_ADDR: "vault:8200"
          BASEPLATE_ZOOKEEPER_ADDR: "zookeeper:2181"
          PIP_OPTIONS:
              from_secret: pip_options
      commands:
          - pip install $PIP_OPTIONS -r requirements-test.txt
          - pytest
      depends_on: [clone]

    - name: "Doctests"
      image: python:3.7-buster
      commands:
          - apt-get update && apt-get install -y libenchant1c2a
          - pip install -r requirements-docs.txt
          - make doctest
      depends_on: [clone]

services:
    - name: cassandra
      image: cassandra:3.11
    - name: memcached
      image: memcached:1.5.6
    - name: redis
      image: redis:4.0.9
    - name: vault
      image: vault:1.0.0
      environment:
          VAULT_DEV_ROOT_TOKEN_ID: "b4c6f298-3f80-11e7-8b88-5254001e7ad3"
    - name: zookeeper
      image: zookeeper:3.4.10
