#!/usr/bin/env python
#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import sys

from . import TestService
from . import ttypes
from . import constants

import thrift.util.fuzzer
thrift.util.fuzzer.fuzz_service(TestService, ttypes, constants)