#!/usr/bin/env python
#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#

from __future__ import print_function
from __future__ import absolute_import

import os
import sys


from . import TestService
from . import ttypes

from thrift.util.remote import Function, Remote
FUNCTIONS = {
    'example_simple': Function('example_simple', 'bool', []),
    'example_throws': Function('example_throws', 'void', [('bool', 'crash', 'bool')]),
}

if __name__ == '__main__':
    Remote.run(FUNCTIONS, TestService, ttypes, sys.argv, default_port=9090)
